version: '3.8'  
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8082"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@i55xvzzbtmq9kyge_low?TNS_ADMIN=/app/oracle_wallet/
      SPRING_DATASOURCE_USERNAME: DSY2201
      SPRING_DATASOURCE_PASSWORD: OracleCloud123
    restart: always
